name: pocket

on:
  workflow_dispatch:

  schedule:
    - cron: "18 0 * * *"

  push:
    branches:
      - master
      - main
      - actions
      - ci
      - "releases/*"
    paths:
      - "pocket/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Save data
        working-directory: ./pocket
        env:
          POCKET_AUTH_JSON_BASE64: "${{ secrets.POCKET_AUTH_JSON }}"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "$POCKET_AUTH_JSON_BASE64" | base64 -d > auth.json
          pocket-to-sqlite fetch pocket.db

      - name: Upload artifacts
        uses: ./
        with:
          upload-to-github: true
          github-artifact-name: pocket
          local-file-path: ./pocket/pocket.db
