name: pocket

on:
  workflow_dispatch:

  schedule:
    - cron: "18 0 * * *"

  push:
    branches:
      - master
      - main
      - actions
      - ci
      - "releases/*"
    paths:
      - "pocket/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Save data
        working-directory: ./pocket
        env:
          POCKET_AUTH_JSON_BASE64: "${{ secrets.POCKET_AUTH_JSON }}"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pocket-to-sqlite fetch --auth <(base64 -d <<< "$POCKET_AUTH_JSON_BASE64") pocket.db

      - name: Upload artifacts
        uses: ./
        with:
          local-file-path: ./pocket/pocket.db
          github-artifact-name: pocket
          remote-file-path: /
          rclone-config: "${{ secrets.RCLONE_CONFIG }}"
